export const transactionTypes: Record<string, string> = {
  'AA00': 'registration of new node user',
  'AA01': 'telemetry of device',
  'AA02': 'part of photo',
  'AA03': 'token transfer',
  'AA05': 'position of tag',
  'AA99': 'unregistration of node',
  'AB00': 'registration of master node',
  'BB00': 'registration of tag',
  'BB01': 'transferring root right for device to another pubkey',
  'CC00': 'sc for buying tokens',
  'PL00': 'registration of company',
  'SC01': 'tracking of device',
  'SC04': 'smart contract for uploading a picture',
  'SC11': 'smart contracts of smart contracts',
  'SW00': 'registration of subwallet',
  'SW01': 'transferring root right for subwallet to another',
  'TP01': 'new type for blockchain',
  'ZZ00': 'closing of smart-contract',
  'ZZ01': 'closing of smart-contract with some errors',
  'ZZ02': 'smart-contract don’t close at all'
};

export const costInTokensMapping: { [key: string]: string } = {
  "AA00": "0",
  "AA01": "1",
  "AA02": "1",
  "AA03": "1",
  "AA05": "1",
  "AA99": "0",
  "AB00": "0",
  "BB00": "3",
  "BB01": '1',
  "CC00": "0",
  "PL00": "100000",
  "SC01": '3',
  "SC04": '3',
  "SC11": "1",
  "SW00": '0',
  "SW01": '1',
  "TP01": "10000",
  "ZZ00": "0",
  "ZZ01": "1",
  "ZZ02": '1',
};